tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern replacement for 'ls'
brew "exa"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Mac App Store command-line interface
brew "mas"
# Library to create, extract, and modify Windows Imaging files
brew "wimlib"
# JavaScript package manager
brew "yarn"
# Password manager that keeps all passwords secure behind one password
cask "1password"
cask "figma"
# Web browser
cask "firefox-developer-edition"
# Menu bar calendar
cask "itsycal"
# Emoji picker optimized for blind people
cask "rocket"
# Open-source BitTorrent client
cask "transmission"
# Tool to hide menu bar icons
cask "vanilla"
# Video communication and virtual meeting platform
cask "zoom"
mas "Codeshot", id: 1541665460
mas "Evernote", id: 406056744
mas "FormatMatch", id: 445211988
mas "Hand Mirror", id: 1502839586
mas "HP Easy Scan", id: 967004861
mas "HP Smart", id: 1474276998
mas "Klib", id: 1196268448
mas "LastPass", id: 926036361
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDF Squeezer 3", id: 504700302
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Trello", id: 1278508951
mas "Twitter", id: 1482454543
mas "UnPlugged", id: 423123087
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
